export const actionType = {
  STATUS_ADD_OP: "STATUS_ADD_OP",
  STATUS_REMOVE_OP: "STATUS_REMOVE_OP",
  UPDATE_ARTICLE: "UPDATE_ARTICLE",
  UPDATE_ARTICLES: "UPDATE_ARTICLES",
  UPDATE_ARTICLES_SCENE: "UPDATE_ARTICLES_SCENE",
};
