export const actionType = {
  STATUS_ADD_OP: "STATUS_ADD_OP",
  STATUS_REMOVE_OP: "STATUS_REMOVE_OP",
  UPDATE_ARTICLE: "UPDATE_ARTICLE",
  UPDATE_ARTICLES: "UPDATE_ARTICLES",
  UPDATE_ARTICLES_SCENE: "UPDATE_ARTICLES_SCENE",
  UPDATE_BOOK: "UPDATE_BOOK",
  UPDATE_BOOKS: "UPDATE_BOOKS",
  UPDATE_BOOKS_SCENE: "UPDATE_BOOKS_SCENE",
  UPDATE_COVID19_SCENE: "UPDATE_COVID19_SCENE",
  UPDATE_LANDING_SCENE: "UPDATE_LANDING_SCENE",
  UPDATE_PROJECTS_SCENE: "UPDATE_PROJECTS_SCENE",
  UPDATE_READER_SCENE: "UPDATE_READER_SCENE",
};
